
puts "RM-Info: Running script [info script]\n"
### Start of PrimeTime Runtime Variables ###

##########################################################################################
# PrimeTime Variables PrimeTime Reference Methodology script
# Script: pt_setup.tcl
# Version: M-2017.06-SP2 (Nov 9, 2017)
# Copyright (C) 2008-2017 Synopsys All rights reserved.
##########################################################################################


######################################
# Report and Results Directories
######################################


set REPORTS_DIR "reports"
set RESULTS_DIR "results"


######################################
# Library and Design Setup
######################################

### Mode : Generic

set search_path ". $ADDITIONAL_SEARCH_PATH $search_path"
set target_library $TARGET_LIBRARY_FILES
set link_path "* $target_library $ADDITIONAL_LINK_LIB_FILES"

# Provide list of Verilog netlist files. It can be compressed --- example "A.v B.v C.v"
set NETLIST_FILES  "${SYN_DELIV_DIR}/${DESIGN_NAME}.mapped.v"
# DESIGN_NAME is checked for existence from common_setup.tcl
if {[string length ${DESIGN_NAME}] > 0} {
} else {
set DESIGN_NAME "IntroProject"  ;#  The name of the top-level design
}

if {[string length ${VC_WORKSPACE}] > 0} {
} else {
    puts "Error: VC_WORKSPACE not set, run 'vc'"
}

if {[string length ${IP_NAME}] > 0} {
} else {
    set IP_NAME "IntroProject"
}

if {[string length ${SYN_DELIV_DIR}] > 0} {
} else {
    set SYN_DELIV_DIR "${VC_WORKSPACE}/ip/${DESIGN_NAME}/syn/results"
}


#######################################
# Non-DMSA Power Analysis Setup Section
#######################################

# switching activity (VCD/SAIF) file 
set ACTIVITY_FILE "" ;# TODO: add waveforms file, should be a vcd file or changes has to be made in pwr-tcl

# strip_path setting for the activity file, this shows where in the waveforms file your design is
set STRIP_PATH "test_${DESIGN_NAME}/u_${DESIGN_NAME}"

## name map file
set NAME_MAP_FILE "" ;# TODO: add namemap file, this is generated by the synthesis tool if you set tell it to (look for N_GEN_SAIF_MAP)


if [string equal ${ANALYSIS_MODE} default]{
} else {
    if {[string length ${ACTIVITY_FILE}] > 0} {
    } else {
        error "Remember to set 'ACTIVITY_FILE' in pwr_setup.tcl"
    }
    if {[string length ${NAME_MAP_FILE}] > 0} {
    } else {
        error "Remember to set 'NAME_MAP_FILE' in pwr_setup.tcl"
    }
}

######################################
# Back Annotation File Section
######################################
# The recommended order is to put the block spefs first then the top so that block spefs are read 1st then top
# For example 
# PARASITIC_FILES "blk1.gpd blk2.gpd ... top.gpd"
# PARASITIC_PATHS "u_blk1 u_blk2 ... top"
# If you are loading the node coordinates by setting read_parasitics_load_locations true, it is more efficient
# to read the top first so that block coordinates can be transformed as they are read in
# Each PARASITIC_PATH entry corresponds to the related PARASITIC_FILE for the specific block"  
# For toplevel PARASITIC file please use the toplevel design name in PARASITIC_PATHS variable."   
set PARASITIC_FILES	 "${SYN_DELIV_DIR}/${DESIGN_NAME}.mapped.spef" 

######################################
# Constraint Section Setup
######################################
set CONSTRAINT_FILES "../syn/rm_dc_scripts/constraints.tcl" ;# reuse constraints file from synthesis



######################################
# End
######################################

### End of PrimeTime Runtime Variables ###
puts "RM-Info: Completed script [info script]\n"
