name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false

      - name: Install verible and lint
        run: |
          sudo apt-get update
          sudo apt-get install verilator
          curl -s https://api.github.com/repos/chipsalliance/verible/releases/latest | grep browser_download_url | grep Ubuntu-20.04 | cut -d '"' -f 4 | wget -qi -
          mkdir verible
          tar -xf verible*.tar.gz -C verible --strip-components=1
          export PATH=$PATH:$PWD/verible/bin
          cd test && make lint


  toolchain:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/cache@v2
        id: cache-riscv-gcc
        with:
          path: /opt/riscv-gcc
          key: ubuntu-20_04-riscv-gcc-rvv0_10

      - name: Install GNU toolchain
        if: steps.cache-riscv-gcc.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install autoconf automake autotools-dev curl python3 libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev
          git clone https://github.com/riscv/riscv-gnu-toolchain
          cd riscv-gnu-toolchain
          git submodule update --init --recursive -- riscv-binutils riscv-dejagnu riscv-gcc riscv-glibc riscv-newlib
          mkdir build && cd build
          ../configure --prefix=/opt/riscv-gcc --with-arch=rv32imc --with-abi=ilp32 --disable-gdb
          make
          sudo make install
          df -h
          cd ..
          rm -rf build


  unit:
    needs: toolchain
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        unit: [lsu, alu, mul, sld, elem, csr, misc]
        main_core: [ibex, cv32e40x]
        exclude:
          - unit: csr
            main_core: cv32e40x
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/cache@v2
        id: cache-riscv-gcc
        with:
          path: /opt/riscv-gcc
          key: ubuntu-20_04-riscv-gcc-rvv0_10

      - name: Abort if no cache
        if: steps.cache-riscv-gcc.outputs.cache-hit != 'true'
        run: exit 1

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install srecord verilator

      - name: Run tests
        run: |
          verilator --version
          cd cv32e40x && git apply ../.github/cv32e40x_ci.patch && cd ..
          export PATH=$PATH:/opt/riscv-gcc/bin
          cd test && make ${{ matrix.unit }} CORE=${{ matrix.main_core }}
