name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  verilator:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/cache@v2
        id: cache-verilator
        with:
          path: /opt/verilator
          key: ubuntu-20_04-verilator-4_210

      - name: Install Verilator
        if: steps.cache-verilator.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install git perl python3 make autoconf g++ flex bison ccache libgoogle-perftools-dev numactl perl-doc libfl2 libfl-dev zlibc zlib1g zlib1g-dev
          git clone https://github.com/verilator/verilator
          unset VERILATOR_ROOT
          cd verilator
          git checkout tags/v4.210
          autoconf
          ./configure --prefix /opt/verilator
          make
          sudo make install
          df -h
          cd ..
          rm -rf verilator


  toolchain:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/cache@v2
        id: cache-riscv-gcc
        with:
          path: /opt/riscv-gcc
          key: ubuntu-20_04-riscv-gcc-rvv

      - name: Install GNU toolchain
        if: steps.cache-riscv-gcc.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install autoconf automake autotools-dev curl python3 libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev
          git clone https://github.com/riscv/riscv-gnu-toolchain
          cd riscv-gnu-toolchain
          mkdir build && cd build
          ../configure --prefix=/opt/riscv-gcc --with-arch=rv32imc --with-abi=ilp32 --disable-gdb
          make
          sudo make install
          df -h
          cd ..
          rm -rf build


  lint:
    needs: verilator
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false

      - uses: actions/cache@v2
        id: cache-verilator
        with:
          path: /opt/verilator
          key: ubuntu-20_04-verilator-4_210

      - name: Install verible and lint
        run: |
          sudo apt-get update
          curl -sSL https://api.github.com/repos/chipsalliance/verible/releases/latest | grep browser_download_url | grep Ubuntu-20.04 | cut -d '"' -f 4 | wget -qi -
          mkdir verible
          tar -xf verible*.tar.gz -C verible --strip-components=1
          export PATH=$PATH:$PWD/verible/bin:/opt/verilator/bin
          cd test && make lint


  unit:
    needs: [toolchain, verilator]
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        unit: [lsu, alu, mul, sld, elem, csr, misc]
        main_core: [ibex, cv32e40x]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/cache@v2
        id: cache-riscv-gcc
        with:
          path: /opt/riscv-gcc
          key: ubuntu-20_04-riscv-gcc-rvv0_10

      - uses: actions/cache@v2
        id: cache-verilator
        with:
          path: /opt/verilator
          key: ubuntu-20_04-verilator-4_210

      - name: Abort if no cache
        if: steps.cache-riscv-gcc.outputs.cache-hit != 'true'
        run: exit 1

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install srecord g++ ccache

      - name: Run tests
        run: |
          export PATH=$PATH:/opt/verilator/bin:/opt/riscv-gcc/bin
          verilator --version
          cp .github/test_configs.conf test/${{ matrix.unit }}/
          cd test && make ${{ matrix.unit }} CORE=${{ matrix.main_core }}
